CREATE TABLE IF NOT EXISTS CUSTOMER (
  ID UUID NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP NULL
);