CREATE TABLE IF NOT EXISTS CUSTOMER_FAVORITE (
  PRODUCT_ID BIGINT NOT NULL,
  CUSTOMER_ID UUID NOT NULL,
  TITLE VARCHAR(100) NOT NULL,
  PRODUCT_IMAGE VARCHAR(255) NOT NULL,
  PRODUCT_PRICE BIGINT NOT NULL,
  PRODUCT_REVIEW_RATE INTEGER NULL,
  PRODUCT_REVIEW_COUNT INTEGER NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP NULL
);